auto: true

markdown: rdiscount
pygments: false
paginate: 8
permalink: /:title

title: lanxinyuchs.github.io
url: lanxinyuchs.github.io
feed: /atom.xml
author_info: <a href="lanxinyuchs.github.io">lanxinyuchs</a>
